language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r ./requirements/requirements_ci.txt >/dev/null

script:
  - make test
  - make lint

env:
  global:
    # COVERALLS_REPO_TOKEN
    - secure: "sMr5cql4+X3n2zySMB9LXCeKWEFovrGXhozJwHAJrHU0HIpKnzf2Ac3ZUzhdcqxtLUPh3mx5SBRANpFhUUBY5FspWnOxdEkjDENvCN1gX32TW8gm3A3P1Y2RWNfg1XpYmFEfSJYsWbWu7FvREO4G1xDOSMJ/wqMpi0vApCvyjorfhG6NsgQrkTtuZR07lsKTgEY989mCGVp80MLDhUre19HGKE0Mdq8LzkiBIDP7oko2J7DaOWQFrQQ91fAucZyTjbQi1n+9u1q7e/UTa4/fXfJsvXoo56ilWkt7aqMko4GFoRba74xclnNMaeG+Dm0Lw8TSWcluUgIY+oIibEuHWIvjAITMb8aAgpsa6N+yFZDK6yiwVeg9zjHpBJKQO29UVppL3z1bFM2wAAjTFtwwH1kQNs/2/iCkOwNnQB8aSr0gyjBEByF3/dyKjiL/W4GXf65VTfCrO5REx9xIUj1INkOkaEhXXTjv1ojC9HVx8PPgy+OJBF8NR9wwnUtLNGoUG1ztEphawU6QrnDnmodHERovOtZjxR1NsTK72/TNWIZFy1KxG9eyIxRiGCX/N5zOY3lDudhteLhrrWMyd/mPYumBqFxuLePCFilPj9C3yUJLR3wbsr3HLdm042fc87DjrWt1hv/fOR0lIfYEd0fyLD6a08pB7Mi1dsscAhlE6bs="